# Generated by Django 5.2.17 on 2026-08-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventorytransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')], max_length=1, unique=True)),
                ('max_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_open_discount', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
