# Generated by Django 5.2.17 on 2026-08-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_discountclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountclass',
            old_name='is_open_discount',
            new_name='open_discount',
        ),
        migrations.RemoveField(
            model_name='discountclass',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='discountclass',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
