# Generated by Django 5.2.17 on 2026-08-22 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sale_options_sale_notes_sale_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountclass',
            options={'ordering': ['code'], 'verbose_name': 'Discount Class', 'verbose_name_plural': 'Discount Classes'},
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory Transaction', 'verbose_name_plural': 'Inventory Transactions'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
    ]
