# Generated by Django 5.2.17 on 2026-08-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_salesperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesperson',
            options={},
        ),
        migrations.AddField(
            model_name='salesperson',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='first_name',
            field=models.CharField(default=14.069444444444445, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesperson',
            name='last_name',
            field=models.CharField(default=14.069444444444445, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesperson',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
