# Generated by Django 5.2.17 on 2026-08-29 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_salesperson_options_salesperson_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='user',
        ),
    ]
