# Generated by Django 5.2.17 on 2026-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_salesperson_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='address',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
