# Generated by Django 5.2.17 on 2026-08-29 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_salesperson_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='salesman',
        ),
        migrations.AddField(
            model_name='sale',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.salesperson'),
        ),
    ]
