# Generated by Django 5.2.17 on 2026-09-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='client',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.salesperson'),
        ),
    ]
