# Generated by Django 5.2.17 on 2026-09-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
