# Generated by Django 5.2.17 on 2026-09-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_client_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='client',
            name='salespersons',
            field=models.ManyToManyField(blank=True, related_name='clients', to='core.salesperson'),
        ),
    ]
