# Generated by Django 5.2.17 on 2026-09-17 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_client_salesperson_client_salespersons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='salespersons',
        ),
    ]
