# Generated by Django 5.2.17 on 2026-09-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_client_salespersons'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='discount_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
