# Generated by Django 5.2.17 on 2026-09-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_client_discount_eligible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='discountclass',
            options={'ordering': ['code'], 'verbose_name': 'Discount Class', 'verbose_name_plural': 'Discount Classes'},
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory Transaction', 'verbose_name_plural': 'Inventory Transactions'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['id'], 'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
        migrations.AlterModelOptions(
            name='salesperson',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Salesperson', 'verbose_name_plural': 'Salespersons'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='discount_eligible',
        ),
        migrations.AddField(
            model_name='client',
            name='discount_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.discountclass'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.client'),
        ),
    ]
