# Generated by Django 5.2.17 on 2026-09-24 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_client_options_alter_discountclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.salesperson'),
        ),
    ]
