# Generated by Django 5.2.17 on 2026-09-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_client_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_permit',
            field=models.FileField(blank=True, null=True, upload_to='business_permits/'),
        ),
    ]
